name: Branch-Test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  SAUCE_CAPABILITIES_OVERRIDES_PATH: 'sauceLabsCapabilities.json'
  ALLOY_ENV: prod
  EDGE_BASE_PATH: ee-pre-prd
jobs:
  alloy-prod-e2e-on-branch:
    name: "Pre Edge: Prod E2E Tests on a branch"
    runs-on: ubuntu-latest
    steps:
      - name: "Testing pre-edge using current branch"
      - uses: actions/checkout@v2
      - name: Get version from package
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run test:functional:build:prod
      - name: Run TestCafe Tests
        run: npx testcafe -q -c 5 'saucelabs:Chrome@latest:macOS 11.00','saucelabs:IE@latest:Windows 10','saucelabs:Firefox@latest:Windows 10','saucelabs:Safari@latest:macOS 11.00'
        env:
          ALLOY_PROD_VERSION: ${{ steps.package-version.outputs.current-version }}
